[phases.setup]
nixPkgs = ["tesseract"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
nixpacksVersion = "1.21.0"
